# Generated by Django 3.1.3 on 2020-11-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elarbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
