# Generated by Django 3.1.3 on 2020-11-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elarbol', '0002_auto_20201107_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre_producto']},
        ),
    ]
