# Generated by Django 3.1.3 on 2020-11-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elarbol', '0003_auto_20201107_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
