# Generated by Django 3.1.3 on 2020-11-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elarbol', '0004_auto_20201107_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
